name: Build

on:
  push:
     # avoid trigerring 2 actions when a release is done and a tag is added
    tags-ignore:
      - v*
    branches: main
  pull_request:
    branches: '*'
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '12.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install jupyterlab==3 jupyter_packaging
    - name: Build the extension
      run: |
        jlpm
        jlpm run eslint:check
        python -m pip install .
        jupyter labextension list 2>&1 | grep -ie "ganymede-logo.*OK"
        python -m jupyterlab.browser_check
    - name: Package  the extension
      if: ${{ github.event_name == 'release' }}
      env:
        TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      run: |
        pip install setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*
